name: TERRAFORM MODULE

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tf_module_base_job:
    uses: acai-consulting/github-terraform-workflows/.github/workflows/tf-module-base-lite.yml@main
    if: ${{ github.event_name == 'pull_request' }}

  tf_check_for_allowed_merge:
    needs: [tf_module_base_job]
    if: ${{  github.event_name == 'pull_request' }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Check for failure condition
        run: |
          # Check if all steps in tf_module_base_job have passed
          if [ "${{ needs.tf_module_base_job.outputs.all_steps_passed }}" != 'true' ]; then
            echo "Base job failed, failing the workflow"
            exit 1
          fi
          echo "All checks passed, proceeding to release"

  tfc_module_release:
    uses: acai-consulting/github-terraform-workflows/.github/workflows/tf-module-release.yml@main
    if: ${{ github.event_name == 'push' }}
    with:
      semantic_release_config_repo: "acai-consulting/github-workflow-configs"
      semantic_release_config_repo_ref: "main"
      release_branch: "main"
    secrets:
      GHE_API_TOKEN: ${{ secrets.GH_ACF_BSL_API_TOKEN }}